---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pgdb-claim
  namespace: demo
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
