---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: mongodb
  namespace: demo
  annotations:
    flux.weave.works/automated: "false"
    flux.weave.works/tag.chart-image: semver:~4.0
spec:
  releaseName: mongodb
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: postgresql
    version: 3.7.1
  values:
    image:
      repository: bitnami/postgresql
      tag: 11.1.0
    postgresqlUsername: postgres
    postgresqlPassword: p0stgre5
    postgresqlDatabase: mydb
    persistence:
      enabled: true
    existingClaim: pgdb-claim
